name: Build & Deploy

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force a new deployment, ignoring path filters'
        required: true
        type: boolean
        default: false

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      web: ${{ steps.filter.outputs.web }}
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Calculate changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            web:
              - 'web/**'
            terraform:
              - 'terraform/**'

  terraform:
    needs: filter
    if: needs.filter.outputs.terraform == 'true' || github.event.inputs.force_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve

  build:
    needs: filter
    if: needs.filter.outputs.web == 'true' || github.event.inputs.force_deploy == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate static site
        run: npm run generate

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: web/.output/public

  deploy-pages:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-aws:
    needs: build
    if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event.inputs.force_deploy == 'true')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: eu-west-1
          output-env-credentials: true

      - name: get caller identity2
        run: |
          aws sts get-caller-identity

      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'dist'

      - name: Invalidate CloudFront cache
        run: |
          for id in $(aws cloudfront list-distributions --query \
            "DistributionList.Items[*].{id:Id,origin:Origins.Items[0].Id}[?origin=='${{ secrets.AWS_S3_BUCKET }}'].id" \
            --output text); do
            aws cloudfront create-invalidation --distribution-id $id --paths "/*"
          done
